{{- if .Values.ingress.enabled -}}
apiVersion: apps/v1
kind: Ingress
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app: kiali
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: kiali
              servicePort: 20001
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
